# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  Vagrant.require_version ">= 1.4.3"

  # Load the preference file
  pref = YAML.load_file("config.yaml")
  # Every Vagrant virtual environment requires a box to build off of.
  if pref['32bit']
    config.vm.box = "ubuntu/xenial32"
  else
    config.vm.box = "ubuntu/xenial64"
  end

  # More Info See: http://docs.vagrantup.com/v2/vagrantfile/machine_settings.html
  config.vm.provider :virtualbox do |vb|
   vb.name = "Elasticsearch-2.x-[ubuntu-16.04]"
   vb.memory = pref['memory']
   vb.cpus = pref['cpus']
   vb.customize ["modifyvm", :id, "--groups", "/Vagrant"]
   vb.gui = false
  end

  # Configure Hostname and Network
  config.vm.hostname = "elastic-search.es.dev"
  #config.vm.network "public_network", ip: pref['ip']
  config.vm.network "private_network", ip: pref['ip']

  # Install the base packages.
  config.vm.provision 'shell', path: './provisioning/bootstrap.sh'
  # Install and configure Elasticsearch
  config.vm.provision 'shell', path: './provisioning/elasticsearch.sh'

end
